version: 2
models:
  - name: dim_customer
    columns:
      - name: customer_key
        tests: [not_null, unique]
  - name: dim_region
    columns:
      - name: region_key
        tests: [not_null, unique]
  - name: fact_sales
    columns:
      - name: order_key
        tests: [not_null]
      - name: customer_key
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_key
