name: sales_demo_project
version: 1.0.0
config-version: 2

profile: sales_demo_project

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
seed-paths: ["seed"]

models:
  sales_demo_project:
    00-bronze:
      +database: BRONZE_DB
      +schema: raw
      +materialized: view
      +tags: ["bronze"]

    01-silver:
      +database: SILVER_DB
      +schema: stg
      +materialized: table
      +on_schema_change: sync_all_columns
      +tags: ["silver"]

    02-gold:
      +database: GOLD_DB
      +schema: marts
      +materialized: table
      +on_schema_change: sync_all_columns
      +tags: ["gold"]
flags:
  require_generic_test_arguments_property: true