version: 2

models:
  - name: dim_customer
    description: Customer dimension table with geographic and segmentation attributes
    config:
      contract:
        enforced: true
    columns:
      - name: customer_key
        description: Primary key for customer dimension
        data_type: number
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null

      - name: customer_name
        description: Customer name
        data_type: varchar
        tests:
          - not_null

      - name: nation_key
        description: Foreign key to nation
        data_type: number
        tests:
          - not_null
          - relationships:
              to: ref('int_nation')
              field: nation_key

      - name: market_segment
        description: Market segment classification
        data_type: varchar

      - name: balance_segment
        description: Customer balance categorization
        data_type: varchar
        tests:
          - not_null
          - accepted_values:
              values: ['Credit', 'Zero Balance', 'Low Balance', 'Medium Balance', 'High Balance']

      - name: account_balance
        description: Current account balance
        data_type: number

      - name: customer_tier
        description: Customer tier classification
        data_type: varchar
        tests:
          - not_null
          - accepted_values:
              values: ['Premium', 'Standard', 'Basic']

